- name: Odoo
  hosts: '{{ host }}'
  become: yes
  roles:
    - ansible-odoo
  vars:
    - odoo_version: 10.0
    - odoo_config_admin_passwd: admin
    - odoo_config_addons_path:
        - "/home/{{ odoo_user }}/server/openerp/addons"
        - "/home/{{ odoo_user }}/server/addons"
